### PR TITLE
GH-639 Save images from quiz settings

### LINKED ISSUE #639: ERROR: Bilder werden in den ShortCodes nicht korrekt angezeigt
So sollte es (wie im Feedback angezeigt) aussehen:
grafik

So sieht es im ShortCode tatsächlich aus:
grafik

Und das ist der Grund: brokenfile.php
grafik

### PR DESCRIPTION
**Pull request by davidszkiba**
Save images from the draft area and rewrite the image URL before returning it as part of the feedback content.

Closes #639

### CODE REVIEW

**Comment by eynimeni** [comment]
@semteacher could you please have a look at these failing actions?

**Comment by semteacher** [comment]
@eynimeni Little bit strange... All working OK locally. erros points to 2 strings which has to be listed in logs... In case of more logs - yes those could be invisible. So I disabled both (they are not critical).... Passed OK under my repo.... Pushed there

**Comment by semteacher** [comment]
@eynimeni  @davidszkiba 
We have multiple behat failures under Moodle 4.4
They caused by the following JS error in the mod_adaptivequiz:
```
module.js:12 Uncaught TypeError: M.core_question_engine.init_form is not a function
    at Object.M.mod_adaptivequiz.init_attempt_form (module.js:12)
    at attempt.php:680
    at YUI._notify (yui_combo.php?rollup/3.18.1/yui-moodlesimple.js:1105)
    at yui_combo.php?rollup/3.18.1/yui-moodlesimple.js:1021
    at YUI._notify (yui_combo.php?rollup/3.18.1/yui-moodlesimple.js:1105)
    at YUI.handleLoader (yui_combo.php?rollup/3.18.1/yui-moodlesimple.js:1250)
    at Y.Loader._finish (yui_combo.php?rollup/3.18.1/yui-moodlesimple.js:8208)
    at Y.Loader._onSuccess (yui_combo.php?rollup/3.18.1/yui-moodlesimple.js:8257)
    at Y.Loader.complete (yui_combo.php?rollup/3.18.1/yui-moodlesimple.js:8496)
    at Y.Loader.onSuccess (yui_combo.php?rollup/3.18.1/yui-moodlesimple.js:8558)
```

It migt be related to outdated branch of mod_adaptivequiz still being in use for tests.
Currently used: 
catmodel_main (Wunderbyte-GmbH/moodle-mod_adaptivequiz)
main (Wunderbyte-GmbH/moodle-adaptivequizcatmodel_catquiz)      
I noticed multiple new branches under Wunderbyte-GmbH/mod_adaptivequiz.
Please, or rebase those branches to the correct code, or tell me which branches I have to rebase onto.

**Comment by davidszkiba** [comment]
@semteacher Our fork is based on the `catmodel_subplugin_with_mod_form_reload` branch of the upstream repo: https://github.com/vtos/moodle-mod_adaptivequiz/tree/catmodel_subplugins_with_mod_form_reload
But I think this upstream branch is also not up-to-date - the last commit is from last year.

After talking to @eynimeni we decided to merge this for now - apart from the 4.4 behat errors, its green and our fork should be merged into upstream soon anyway.

Thanks for making the other moodle versions green!

**Pull request merged**
