### PR TITLE
Dev test generator feature

### PR DESCRIPTION
**Pull request by semteacher**
New generator method whach allows to create a catquiz instance via DB with limiration - one-time visit of "Settings" page required (have not mamaged with default settings whcih requires ID in JSON data)

### CODE REVIEW

**Review by eynimeni — COMMENTED** [review]
looks good to me. 
but some behat actions are still failing. please make sure they pass before merging.

and please @davidszkiba take a look into change of values in test results.

**Review by davidszkiba — COMMENTED** [review]
LGTM, just found one TODO and I'm not sure if you wanted to include this in this PR.

**Comment by davidszkiba** [comment]
> looks good to me. but some behat actions are still failing. please make sure they pass before merging.
> 
> and please @davidszkiba take a look into change of values in test results.

I'm still in the progress of getting #323 green. If that works, I think the changes in this PR can be rebased on it and then the values should be fine.

**Comment by semteacher** [comment]
@davidszkiba 
I have rebased this branch onto latest dev and all tests are "green"
Regarding "Todo". Probably it would be better to have JSON with predefined feedbacks. Right now I skip it bacause in behat there is no "ResetAfterTest" and IDs being constantly updated. Anyway, not sure how widely useful this generator could be (to invest more time). For current tests I consider it as enough.

**Comment by davidszkiba** [comment]
> @davidszkiba I have rebased this branch onto latest dev and all tests are "green" Regarding "Todo". Probably it would be better to have JSON with predefined feedbacks. Right now I skip it bacause in behat there is no "ResetAfterTest" and IDs being constantly updated. Anyway, not sure how widely useful this generator could be (to invest more time). For current tests I consider it as enough.

@semteacher Ok good, I think then you're free to merge this

**Comment by semteacher** [comment]
Have just added one more scanarion. Will megre if it will be OK

**Pull request merged**
